version: "3.8"
services:
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://red-cv4qvijtq21c73fe9t7g:6379

  test:
    build: .
    command: npm run test
    depends_on:
      - redis

volumes:
  redis_data:
